services:
  postgres:
    image: postgres:16.3
    environment:
      - POSTGRES_PASSWORD=1234
    ports:
      - 5432:5432
    volumes:
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init.sql